apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: development
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
