apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceadjustments.k8s.jonwraymond.io
spec:
  group: k8s.jonwraymond.io
  names:
    kind: ResourceAdjustment
    listKind: ResourceAdjustmentList
    plural: resourceadjustments
    singular: resourceadjustment
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true

      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRepo:
                  type: object
                  properties:
                    url:
                      type: string
                    credentialsSecret:
                      type: string
                mappings:
                  type: array
                  items:
                    type: object
                    properties:
                      filePath:
                        type: string
                      resourcePath:
                        type: string
                      qosClass:
                        type: string
                        enum: [ "Burstable", "Guaranteed" ]
                      manage:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: boolean
                              memory:
                                type: boolean
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: boolean
                              memory:
                                type: boolean
                      recommendations:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
