apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-resource-adjuster
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitops-resource-adjuster
  template:
    metadata:
      labels:
        name: gitops-resource-adjuster
    spec:
      serviceAccountName: gitops-resource-adjuster
      containers:
      - name: operator
        image: jonwraymond/gitops-resource-adjuster:latest
        ports:
        - containerPort: 8080
