apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-adjuster-operator
  namespace: operators
subjects:
- kind: ServiceAccount
  name: resource-adjuster-operator
  namespace: operators
roleRef:
  kind: Role
  name: resource-adjuster-operator
  apiGroup: rbac.authorization.k8s.io
