apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: operators
  name: resource-adjuster-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["k8s.jonwraymond.io"]
  resources: ["resourceadjustments"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
