apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-resource-adjuster
  namespace: operators
subjects:
- kind: ServiceAccount
  name: gitops-resource-adjuster
  namespace: operators
roleRef:
  kind: Role
  name: gitops-resource-adjuster
  apiGroup: rbac.authorization.k8s.io
