apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: default
type: Opaque
data:
  # Replace `apiToken` or `sshKey` with your base64-encoded credentials
  apiToken: <base64-encoded-api-token>
  sshKey: <base64-encoded-ssh-key>
