apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceadjustments.jonwraymond.com
  group: jonwraymond.com
  names:
    kind: ResourceAdjustment
    listKind: ResourceAdjustmentList
    plural: resourceadjustments
    singular: resourceadjustment
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRepo:
                  type: object
                  properties:
                    url:
                      type: string
                    credentialsSecret:
                      type: string
                mappings:
                  type: array
                  items:
                    type: object
                    properties:
                      filePath:
                        type: string
                      resourcePath:
                        type: string
                      recommendations:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string

                conditions:
                  type: object
                  properties:
                    vpaRecommendation:
                      type: boolean
